# Generated by Django 3.0.5 on 2021-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secMes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='userid',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
